---
- hosts: all
  name: Prepares a SELinux workshop
  become: yes
  connection: local
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
  tasks:

  - name: Reapply the role
    include_role:
        name: linux-system-roles.selinux

  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3-policycoreutils
      - policycoreutils-devel
      - policycoreutils-newrole
      - selinux-policy-doc
      - setroubleshoot-server
      - setools-console
      - make
      - gcc-c++
      - libcurl-devel.x86_64
      - rpm-build

  - name: Create dir with working files
    file:
      path: /root/selinuxlab
      state: directory
      mode: 0755

  - name: Ensure SELinux test app source is on the system
    copy:
      src: files/testapp.c
      dest: /root/selinuxlab
      mode: 0755

  - name: Ensure Makefile for the test app is copied to the system
    copy:
      src: files/Makefile
      dest: /root/selinuxlab
      mode: 0755

  - name: Ensure SELinux test app service file is on the system
    copy:
      src: files/testapp.service
      dest: /root/selinuxlab/testapp.service
      mode: 0644

  - name: Compile the testapp
    shell:
      cmd: "make -f /root/selinuxlab/Makefile"
      chdir: /root/selinuxlab

  - name: Install the testapp
    shell:
      cmd: "make install -f /root/selinuxlab/Makefile"
      chdir: /root/selinuxlab

...
